package com.example.mal2017_assessmentmodule.models;

import com.google.gson.annotations.SerializedName;

/**
 * User Model - Represents a user in the system (Guest or Staff).
 *
 * This model is used for:
 * - API communication (Volley with Gson)
 * - SQLite database storage
 * - In-memory user data management
 *
 * Design Pattern: Data Transfer Object (DTO)
 * - Encapsulates user data
 * - Provides type-safe access to properties
 * - Supports serialization/deserialization
 *
 * @author BSCS2509254
 * @version 1.0
 */
public class User {

    // User ID (auto-generated by API)
    @SerializedName("user_id")
    private int userId;

    // Username for login
    @SerializedName("username")
    private String username;

    // Password (hashed on server, plain text in local storage - encrypted recommended)
    @SerializedName("password")
    private String password;

    // User's first name
    @SerializedName("firstname")
    private String firstname;

    // User's last name
    @SerializedName("lastname")
    private String lastname;

    // Email address
    @SerializedName("email")
    private String email;

    // Contact number
    @SerializedName("contact")
    private String contact;

    // User type: "guest" or "staff"
    @SerializedName("usertype")
    private String usertype;

    /**
     * Default constructor required for API deserialization
     */
    public User() {}

    /**
     * Full constructor for creating user objects
     */
    public User(String username, String password, String firstname, String lastname,
                String email, String contact, String usertype) {
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.contact = contact;
        this.usertype = usertype;
    }

    // Getters and Setters
    public int getUserId() { return userId; }
    public void setUserId(int userId) { this.userId = userId; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getFirstname() { return firstname; }
    public void setFirstname(String firstname) { this.firstname = firstname; }

    public String getLastname() { return lastname; }
    public void setLastname(String lastname) { this.lastname = lastname; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getContact() { return contact; }
    public void setContact(String contact) { this.contact = contact; }

    public String getUsertype() { return usertype; }
    public void setUsertype(String usertype) { this.usertype = usertype; }

    /**
     * Get full name for display purposes
     */
    public String getFullName() {
        return firstname + " " + lastname;
    }

    /**
     * Check if user is staff
     */
    public boolean isStaff() {
        return "staff".equalsIgnoreCase(usertype);
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", email='" + email + '\'' +
                ", usertype='" + usertype + '\'' +
                '}';
    }
}